[package]
name = "validate_robust_seq"
version = "0.1.0"
authors = ["Titus Tienaah <titus.intdxdt@gmail.com>"]

[dependencies]
test_float_overlap = { git = "https://github.com/intdxdt/test_float_overlap", branch = "master" }